#!/usr/bin/env bash
set -euo pipefail

if [[ $1 != "run" ]]; then
    printf  '%s %s\n' "Only supports the 'run' command, but was:" $1
    exit 1
fi

# Rewrite as Charliecloud command
cc="ch-run"
bind_next=0
seen_image=0
seen_sh=0
seen_c=0
append=0

shift 1
for arg in "$@"
do
    if [[ $bind_next -eq 1 ]]; then
        cc="$cc $arg"
        bind_next=0
        continue
    fi

    if [[ $arg == "-B" ]]; then
        cc="$cc -b"
        bind_next=1
        continue
    fi
+
    if [[ $seen_image -eq 0 ]]; then
        image="${arg/'docker://'}"
        chaplin $image

        image="${image/':'*}"
        cc="$cc $image --"

        seen_image=1
        continue
    fi

    if [[ $seen_sh -eq 1 && $seen_c -eq 1 ]]; then
        cc="$cc \"$arg"
        seen_sh=0
        seen_c=0
        append=1
    else
        cc="$cc $arg"
    fi

    if [[ $arg == "sh" ]]; then
        seen_sh=1
    fi

    if [[ $arg == "-c" ]]; then
        if [[ $seen_sh -eq 1 ]]; then
            seen_c=1
        else
            seen_sh=0
        fi
    fi
done

if [[ $append -eq 1 ]]; then
    cc="$cc\""
fi

eval $cc
