import v6_client;
import v6_node;
import v6_server;

let server := start_server(5000);
server.waitUntilStarted();

let server_url := "http://" + server.address + ":5000";

let session := login("admin", "password", server_url);
let token := session.access_token;

let collaboration := create_collaboration("collab", "1", server_url, token);
let node_info := create_node(collaboration.id, server_url, token);

let node := start_node(node_info.api_key, server.address, 5000);
node.waitUntilStarted();

