FROM rust:1 as build

RUN apt-get update && apt-get install -y \
    cmake \
 && rm -rf /var/lib/apt/lists/*

# Copy over relevant crates
COPY ./brane-clb ./brane-clb

# Build an optimized binary
WORKDIR /brane-clb
RUN cargo build --release

# Define final image
FROM ubuntu:20.04

# Copy `brane-clb` from build stage
COPY --from=build /brane-clb/target/release/brane-clb .

ENTRYPOINT [ "./brane-clb" ]
