FROM ubuntu:20.04

ENV VERSION="3.0.2"
ENV RELEASE="xenon-grpc-shadow-$VERSION"

RUN apt-get update && apt-get install -y \
    openjdk-11-jre-headless \
 && rm -rf /var/lib/apt/lists/*

ADD "https://github.com/xenon-middleware/xenon-grpc/releases/download/v$VERSION/$RELEASE.tar" .

RUN tar -xf "$RELEASE.tar" \
 && mv "$RELEASE" "xenon" \
 && rm "$RELEASE.tar"

RUN mkdir /keys

EXPOSE 50051
ENTRYPOINT ["/xenon/bin/xenon-grpc"]